config/routes.rb
Well::Application.routes.draw do
 
  root to: "welcome#index"

  get "logout" => "sessions#destroy", as: "logout"
  get "login" => "sessions#new", as: "login"
  get "signup" => "signup#index"
  get "profile/(:section)" => "users#profile", as: "profile"
  get 'demo' => "users#demo", as: "demo"
  get 'users/request_password_reset' => 'users#request_password_reset', as: "request_password_reset"
  post 'users/send_password_reset' => 'users#send_password_reset', as: "send_password_reset"
  get 'reset/(:password_reset_token)' => 'users#reset_password', as: "reset_password"
  put 'users/(:id)/update_password' => 'users#update_password', as: "update_password"

  # TODO: A welcome view:
  # "Welcome to Ettúi, {let's get started}"

  get "bookmarklet/preview" => "jsonp#preview", as: "bookmarklet_preview"
  get "legal/tos"
  get "legal/pp"
  get "demo/complete" => "users#complete", as: "completion"
  get "introduction/start", as: "introduction"
  get "introduction/trying_it"
  get "introduction/finish"
  get "json_quote_creation", controller: "json"
  get "json_tag_creation", controller: "json"
  get "quote_creation", controller: "jsonp"
  get "tag_creation", controller: "jsonp"
  resources :users, except: [:index, :profile]
  resources :sessions, only: [:new, :create, :destroy]
  resources :boards, only: [:show] do
    resources :quotes, only: [:destroy, :show] do
      resources :tags, only: [:destroy, :create]
    end
  end
end

app/models/quote.rb
class Quote < ActiveRecord::Base

  scope :since, ->(date) { where("created_at > ?", date) }
  
  has_and_belongs_to_many :boards
  belongs_to :source
  has_and_belongs_to_many :tags

  delegate :favicon, to: :source

  def self.in_board(board)
    board.quotes
  end

  def self.filter_by_source_ids(source_ids)
    if source_ids.empty?
      all
    else
      where(source_id: source_ids)
    end
  end

  def self.new_quote_count(user)
    where("created_at > ?", user.last_active_at).count
  end

  def self.filter_by_text(filter_text)
    if filter_text.blank?
      all
    else
      where("text LIKE ?", "%#{filter_text}%")
    end
  end

  def has_tag(tag_name)
    tags.map(&:name).include?(tag_name)
  end

  def title
    if readability_title
      readability_title
    else
      url
    end
  end

  def unique_tags
    tags.distinct
  end

  def classes_for(user)
    # if new_since_last(user)
    #   default_classes << " unread"
    # else
    #   default_classes
    # end
    default_classes
  end

  def excerpt

  end

  def default_classes
    "c-quote q-#{id}"
  end

  def highlight search_query
    if search_query.nil?
      query = ""
    end

    if search_query
      query = search_query
    end
    QuoteHighlighter.hilight(self, query)
  end

  def font_size
    case
    when text.length < 140
      "big"
    when text.length > 280
      "small"
    else
      ""
    end
  end

  def source_date
    "#{created_at.day} #{created_at.strftime("%b")}"
  end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :authorize, except: :show 

  def show
    @quote = Quote.find(params[:id])
    @board = @quote.boards.first
    @user = @board.users.first
    @search = Search.new
  end

  def destroy
    @quote = Quote.find(params[:id])

    if @quote.destroy
      redirect_to board_path(current_user.board)
    end
  end
end

app/views/quotes/_input_new_tag.html.erb
<%= form_for quote.tags.build, url: board_quote_tags_path(board, quote), class: "c-tag_form" do |f| %>
  <%= f.text_field :name, placeholder: "New tag title", class: "c-tag_form__input" %>
  <%= f.submit "Add", class: "c-tag_form__button" %>
<% end %>

app/views/quotes/_quote.html.erb
<div class="<%= quote.classes_for(current_user) %>">
   <!-- Title and Favicon !-->
  <div class="c-quote__metadata__container">
    <div class="c-quote__metadata c-quote__metadata--title-and-author c-quote__metadata--secondary">
      <%= image_tag quote.favicon, class: "c-quote__favicon" %>
      <%= link_to quote.url, class: "c-quote__title is-truncated" do %>
        <%= quote.title %>
        <%= " by #{quote.readability_author}" unless quote.readability_author.nil? %>
      <% end %>
    </div>
    <div class="c-quote__metadata c-quote__metadata--primary">
      <p class="c-quote__timestamp subtitle--all-caps subtitle--secondary" title="Date of creation.">
        <%= quote.source_date %>
      </p>
    </div>
  </div>

  <!-- Quote !-->
  <h1 class="c-quote__content <%= quote.font_size %>">
    <%= link_to_if(controller_name.eql?("boards"), (raw quote.highlight(@search.query)), board_quote_path(@board, quote)) %>
  </h1>

  <!-- Tags !-->
  <% if current_user && controller_name.eql?("quotes") %>
    <!-- (fa_icon "trash-o") !-->
    <%= link_to (fa_icon "trash-o"), board_quote_path(@board, quote), method: :delete, class: "u-block c-quote__remove", title: "Delete this quote." %>
  <% end %>
  <div class="c-quote__tags">
      <ul class="u-inline-block">
        <% quote.unique_tags.each do |tag| %>
            <%= render partial: 'tags/tag', locals: { quote: quote, tag: tag } %>
        <% end %>
      </ul>
      <% if current_user && controller_name.eql?("quotes") %>
        <%= render partial: 'quotes/input_new_tag', locals: { quote: quote, board: @board } %>
      <% end %>
  </div>
</div>

app/views/quotes/show.html.erb
<div class="container--full-size beige flex direction--column space-between center--vertical quote--show t-theme2">
	<%= link_to "ettúi.", board_path(@quote.boards.first), class: "c-ettui-logo" %>
	<% if @quote %>
		<%= render @quote %>
	<% end %>
	<div class="quote-author centered">
		<h3 class="subtitle subtitle--all-caps">Curated by</h3>
		<% if @user.twitter_image_url.nil? %>
		<%= link_to current_user.name || current_user.email, profile_path, {:style=> 'background-color: rgba(0, 0, 0, .07); padding: 1px 6px 3px; border-radius: 8px; color: #666; font-weight: 600; max-width: 100px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;'}  %>
		<% else %>
			<%= link_to image_tag(@user.twitter_image_url, class: "a-profile_image"), @user %>
		<% end %>
	</div>
</div>