config/routes.rb
Well::Application.routes.draw do
 
  root to: "welcome#index"

  get "logout" => "sessions#destroy", as: "logout"
  get "login" => "sessions#new", as: "login"
  get "signup" => "signup#index"
  get "profile/(:section)" => "users#profile", as: "profile"
  get 'demo' => "users#demo", as: "demo"
  get 'users/request_password_reset' => 'users#request_password_reset', as: "request_password_reset"
  post 'users/send_password_reset' => 'users#send_password_reset', as: "send_password_reset"
  get 'reset/(:password_reset_token)' => 'users#reset_password', as: "reset_password"
  put 'users/(:id)/update_password' => 'users#update_password', as: "update_password"

  # TODO: A welcome view:
  # "Welcome to Ettúi, {let's get started}"

  get "bookmarklet/preview" => "jsonp#preview", as: "bookmarklet_preview"
  get "legal/tos"
  get "legal/pp"
  get "demo/complete" => "users#complete", as: "completion"
  get "introduction/start", as: "introduction"
  get "introduction/trying_it"
  get "introduction/finish"
  get "json_quote_creation", controller: "json"
  get "json_tag_creation", controller: "json"
  get "quote_creation", controller: "jsonp"
  get "tag_creation", controller: "jsonp"
  resources :users, except: [:index, :profile]
  resources :sessions, only: [:new, :create, :destroy]
  resources :boards, only: [:show] do
    resources :quotes, only: [:destroy, :show] do
      resources :tags, only: [:destroy, :create]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  # Establish relation to quotes
  has_and_belongs_to_many :boards, join_table: :subscriptions
  before_destroy :destroy_boards

  attr_accessor :password, :password_confirmation

  # Encrypt password before saving it to the database
  before_save :encrypt_password

  # If save was successful, set a token for the user
  after_save :initialize_user

  has_many :quotes, dependent: :destroy

  # Form validations
  validates_uniqueness_of :email, unless: :provider_or_guest?
  validates_presence_of :email, :password, :password_confirmation, on: :create_or_save, unless: :guest?
  validates_presence_of :email, :password, :password_confirmation, on: :update, allow_blank: true
  validates_confirmation_of :password, unless: :provider_or_guest?

  def board
    boards.first
  end

  def unique_tags
    board.tags.uniq
  end

  def quote_count
    board.quotes.count
  end

  def source_count
    board.quotes.pluck(:source_id).uniq.count
  end

  def tag_count
    board.tags.uniq.count
  end

  def name_or_email
    name || email
  end

  def update_password(password)
    self.password = password
    self.password_reset_token = nil
    self.password_reset_sent_at = nil
  end

  def create_password_reset_token
    self.password_reset_token = SecureRandom.hex(13)
    self.password_reset_sent_at = Time.zone.now
    save!
  end

  def send_password_reset
    create_password_reset_token
    UserMailer.password_reset(self).deliver_now
  end

  # Generates and sets a token for the new user
  private
  def initialize_user
    # Give the new user a token
    if self.token.nil?
      token = SecureRandom.hex(13)

      # Make sure token is unique
      while User.find_by_token(token)
        token = SecureRandom.hex(13)
      end

      # We now have a token, so lets set it
      self.update(token: token)

      # Initiate a board for the user
      self.boards << Board.create({ user_id: self.id, name: "My board" })
    end
  end

  def destroy_boards
    boards.each do |board|
      board.destroy unless board.has_subscribers?
    end
  end

  # Encrypts and stores the provided password
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def provider_or_guest?
    provider? || guest?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:new, :create, :update, :complete, :demo, :reset_password, :update_password, :send_password_reset, :request_password_reset]

  def new
    @user = User.new

    if current_user
      redirect_to board_path(current_user.board)
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      # If we're finalizing a demo user
      if user_params[:guest].eql?("false")
        @user.create_password_reset_token
        redirect_to reset_password_path(@user.password_reset_token)
      else
        redirect_back(fallback_location: root_path, notice: "User details were updated.")
      end
    else
      redirect_back(fallback_location: root_path, notice: "Details could not be updated.")
    end
  end

  def create

    # A request from the bookmark will not contain params
    respond_to do |format|
      format.html {
        @user = user_params ? User.new(user_params) : User.new_guest

        if @user.save
          session[:user_id] = @user.id # Establish a session
          redirect_to introduction_path, notice: "You successfully signed up."
        else
          render action: "new", notice: "A user with that email address already exists. If it's you, please try the login page."
        end
      }

      format.json {
        authenticate_with_http_basic do |email, password|
          authentication = Authentication.new(email, password)
  
          # Decode passwords
          passwords = Base64.decode64(password)
          password = passwords.split(/:/, 2).first
          password_confirmation = passwords.split(/:/, 2).last
  
          # Build user_params
          user = {}
          user[:email] = email
          user[:password] = password
          user[:password_confirmation] = password_confirmation

          @user = User.new(user)
          @validation_status = ''
          @invalid = false

          if User.where(email: @user.email).exists?
            @invalid = true
            @validation_status = 'This email is already registered'
          else
            if !password.eql?(password_confirmation)
              @invalid = true
              @validation_status = 'The passwords do not match'
            end
          end
        end

        if @user.save && !@invalid
          session[:user_id] = @user.id # Establish a session
          @validation_status = ''
          render json: { user_email: @user.email, user_token: @user.token, user_id: @user.id, status: @validation_status }
        else
          render json: { user_email: '', user_token: '', user_id: '', status: @validation_status }
        end
      }
    end

    
  end

  def demo
    if current_user
      redirect_to board_path(current_user.board), notice: "You can't create a demo user when you are already signed in."
    else
      @user = CreateGuest.create
      if @user.save

        # Initiate a session
        session[:user_id] = @user.id

        # Introduce them to their bookmarklet
        redirect_to introduction_path
      end
    end
  end

  def complete
    if current_user && current_user.guest?
      @user = current_user
      render "complete", notice: "Complete your demo account."
    else
      redirect_to root_path, notice: "You need to be signed in as a demo user to do that."
    end
  end

  def profile

    @section = params[:section] || "settings"

    if current_user && current_user.guest?
      @user = current_user
      redirect_to completion_path, notice: "Complete your demo account to fully use Ettúi."
    elsif current_user
      @user = current_user
      @board = @user.board
      render "profile", notice: nil
    else
      redirect_to root_path, notice: "You need to sign in to view that page."
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to signup_path
  end

  def reset_password
    if params[:password_reset_token]
      @user = User.find_by(password_reset_token: params[:password_reset_token])
    else
      redirect_to request_password_reset_path, :notice => "Your password could not be reset. Please try again."
    end
  end

  def request_password_reset
    if current_user
      @user = current_user
      render :notice => "You are about to request a new password for #{@user.name || @user.email}"
    end
  end

  def send_password_reset
    @user = User.find_by(email: params[:email])
    if @user
      @user.send_password_reset
      redirect_to login_path, :notice => "A link where you can reset your password has been sent to your mail."
    else
      redirect_to request_password_reset_path, :notice => "Your password could not be reset. Please try again."
    end
  end

  def update_password
    @user = User.find(params[:id])

    if (@user.password_reset_sent_at - 1.hour.ago) > 0
      @user.update_password(params[:password])

      if @user.save
        redirect_to login_path, :notice => "Your password is updated."
      end
    else
      redirect_to request_password_reset_path, :notice => "Your opportunity to reset your password has expired. Please try again."
    end
  end

  private
  # Using a private method to encapsulate the permissible parameters is
  # just a good pattern since you'll be able to reuse the same permit
  # list between create and update. Also, you can specialize this method
  # with per-user checking of permissible attributes.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :token, :twitter_image_url, :name, :new_user, :guest)
  end

end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= f.hidden_field :new_user, value: true %>
  <div class="first field">
    <%= f.text_field :email, placeholder: "Electronic mail address", type: "email" %>
    <p class="validation"><%= @user.errors[:email].first %></p>
  </div>
  <div class="field">
    <%= f.password_field :password, placeholder: "Password", class: 'sec' %>
    <p class="validation"><%= @user.errors[:email].first %></p>
  </div>
  <div class="last field">
    <%= f.password_field :password_confirmation, placeholder: "Password again", class: 'thi' %>
    <p class="validation"><%= @user.errors[:email].first %></p>
  </div>
  <div class="actions">
    <%= f.submit "Sign up with e–mail", class: "stay button" %>
  </div>
<% end %>

app/views/users/bookmarklet.html.erb
<!--

  A page containing everything the user needs to set up his or her bookmarklet.
  For Desktop and mobile.

!-->
<%= render "bookmarklet" %>

app/views/users/complete.html.erb
<% if flash[:notice] %>
  <div class="c-status_message success"><%= flash[:notice] %></div>
<% end %>
<div class="o-overlay t-theme2">
  <div class="c-modal__window">
    <div class="modal__content">
      <%= link_to "ettúi", :back, class: "c-ettui-logo" %>
      <h1>
        Make the demo yours.
      </h1>
      <p>
        In order to connect this account with you, we need your e-mail address. It is only used to manage your account.
      </p>
      <div class="profile-details naked">
        <%= form_for @user do |f| %>
          <%= f.hidden_field :guest, :value => false %>
          <%= f.text_field :email, :placeholder => "Your e-mail address" %>
         <%= f.submit "Confirm account", :class => "button" %>
        <% end %>
        <p>
          After this you'll be able to set a password.  
        </p>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render "header" %>
<div class="c-landing_page o-full_screen o-full_screen--centered u-clearfix">
  <div class="o-half_screen">
    <h1 class="c-landing_page__title">
       You should always have with you the great things you’ve read.
    </h1>
    <p class="c-landing_page__text">    
      Ettúi is made to easily save and catalogue those gems so that they’re accessible from anywhere—at any time.
    </p>
    <%= link_to "Try our demo", demo_path, :class => "c-button c-button--secondary" %>
    <%= link_to "Create an account", signup_path, :class => "c-button c-button--primary" %>
  </div>
  <div class="o-half_screen u-text-align-center">
    <%= image_tag "landing_page-image@2x.png", :alt => "Ettui product image.", :class => "c-landing_page__image" %>
  </div>
</div>
<footer class="c-landing_page__footer">
  <p class="c-landing_page__footer_title">Copyright(C) 2015 Henrik Wiberg, Hannes Gustafsson</p>
</footer>
<% if current_user %>
  <div class="c-test_data">
      <h6><%= current_user.name %></h6>
      <%= link_to "Logout", logout_path %>
  </div>
<% end %>

app/views/users/introduction.html.erb
<div class="t-theme2">
  <div class="o-body">
    <div class="c-introduction">
      <h1 class="c-ettui-logo">ettúi</h1>
      <h2 class="c-introduction__title--section">Installing your bookmarklet.</h2>
       <!--

        Segment navigation controller

      !-->
      <div class="c-segment_controller">
        <ol class="c-segment_controller__list">
          <li class="c-segment_controller__option is-active" data-target="js-section--desktop">Computer</li><li class="c-segment_controller__option" data-target="js-section--mobile">Phone/Tablet</li>
        </ol>
      </div>
      <!--

        Desktop

      !-->
      <div class="c-introduction__section js-section--desktop">
        <ul class="c-introduction__step_list">
          <li>
            <p class="c-introduction__step_title">1</p>
            Drag the button below to your bookmarks bar.
          </li>
        </ul>
        <% if Rails.env.development? %>
          <a class="c-introduction__bookmarklet" href="javascript:(function() {
          document.body.appendChild(document.createElement('script')).src='http://localhost:3000/bookmarklet_local.js';
          current_user_token = '<%= current_user.token %>';
          })();">Ettúi Bookmarklet</a>
        <% elsif Rails.env.production? %>
          <a class="c-introduction__bookmarklet" href="javascript:(function() {
          document.body.appendChild(document.createElement('script')).src='https://notedapp.herokuapp.com/bookmarklet.js';
          current_user_token = '<%= current_user.token %>';
          })();">Ettúi Bookmarklet</a>
        <% end %>
         <p class="c-introduction__description">The bookmarks bar is located below the address bar.</p>
         <%= link_to "Continue to my board", continue_path, :class => "c-button c-button--primary" %>
         <!-- <a href="#!" class="c-introduction__button c-introduction__button--next">Try out the bookmarklet</a> -->
      </div>
      <!--

        Mobile

      !-->
      <div class="c-introduction__section js-section--mobile">
        <ul class="c-introduction__step_list">
          <li>
            <p class="c-introduction__step_title">1</p>
            Create a new bookmark and give it a name, i.e. Save to Ettúi.
          </li><li>
            <p class="c-introduction__step_title">2</p>
              Copy the javascript snippet below using 'Select All' or something similar.
              <div class="c-introduction__bookmarklet c-introduction__bookmarklet--mobile">
                <code>
                  javascript:(function() {
                  document.body.appendChild(document.createElement('script')).src='https://notedapp.herokuapp.com/bookmarklet.js';
                  current_user_token = '<%= current_user.token %>';
                  })();
                </code>
              </div>
          </li><li>
            <p class="c-introduction__step_title">3</p>
            Now choose to Edit the bookmark you just created and paste the javascript snippet.
          </li>
        </ul>
        <%= link_to "Continue to my board", continue_path, :class => "c-button c-button--primary" %>
        <!-- <a href="#!" class="c-introduction__button c-introduction__button--next">Try out the bookmarklet</a> -->
      </div>
      <!--

        Tryout

      !-->
      <div class="c-introduction__section js-section--tryout">
        <h2 class="c-introduction__title--section">Now let's try using it.</h2>
        <p>Highlight the text below and click on the bookmarklet.</p>
        <blockquote class="c-introduction__quote">
          “The mistakes, errors, dead-ends, and wrong turns you make are going to be more important than the projects that just turned out okay.”
        </blockquote>
        <%= link_to "Continue to my board", continue_path, :class => "c-button c-button--primary" %>
        <!-- <div class="c-test_data">
        <% if current_user %>
          <h6><%= current_user.name %></h6>
          <%= link_to "Logout", logout_path %>
        <% end %>
        </div>
      </div> -->
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="o-overlay m-scene t-theme2">
  <div class="c-modal__window">
    <div class="modal__content">
      <%= link_to "ettúi", '/', class: "c-ettui-logo" %>
      <h1>
        You're one step away<br/>from your personal archive.
      </h1>
      <%= render "form" %>
      <p class="secondary">
        By signing up you agree to the<br/>
        <%= link_to "Privacy Policy", "legal/pp" %> and
        <%= link_to "Terms of Service", "legal/tos" %>
      </p>
      <p>
        Already have an account?
        <%= link_to "Log in", login_path %>
      </p>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<div class="c-sidebar_container">
  <div class="icon-menu js-toggle-menu"></div>
  <div class="profile-section profile-data profile-container">
    <img src="<%= @user.twitter_image_url %>"/>
    <h1><%= @user.name_or_email %></h1>
    <p><%= @user.twitter_description || "No description" %></p>
    <ul class="c-sidebar_container__list">
      <li>
        <%= link_to "Account details", profile_path(:settings), class: "c-button c-button--text--primary" %>
      </li>
      <li>
        <%= link_to "Bookmarklet", profile_path(:bookmarklet), class: "c-button c-button--text--primary" %>
      </li>
      <li>
        <%= link_to "Reset password", profile_path(:reset_password), class: "c-button c-button--text--primary" %>
      </li>
    </ul>
  </div>
  <div class="profile-section profile-data profile-link-back">
    <%= link_to "Back to your Quotes", board_path(@user.board), class: "c-button c-button--primary" %>
    <%= link_to "ettúi", root_url, class: "c-ettui-logo" %>
  </div>
</div>
<div class="o-content_container">
  <div class="icon-menu js-toggle-menu content-menu"></div>
  <div class="o-title_container">
    <% if @section.eql?("settings") %>
      <h1 class="o-content_container__title settings-title">
        Account details.
      </h1>
      <div class="o-quotes_container">
        <div class="profile-section profile-details">
          <%= form_for @user do |f| %>
           <%= f.label :email, "Your e-mail", :class => "subtitle subtitle--all-caps" %>
           <%= f.text_field :email, :placeholder => "No e-mail set" %>
           <%= f.label :name, "Your name", :class => "subtitle subtitle--all-caps" %>
           <%= f.text_field :name %>
           <%= f.label :twitter_description, "Description", :class => "subtitle subtitle--all-caps" %>
           <%= f.text_area :twitter_description %>
           <%= f.label :twitter_image_url, "Profile image", :class => "subtitle subtitle--all-caps" %>
           <%= f.text_field :twitter_image_url %>
           <%= f.submit "Update Account details", :class => "c-button c-button--primary" %>
          <% end %>
        </div>
      </div>
    <% end %>
    <% if @section.eql?("reset_password") %>
      <h1 class="o-content_container__title settings-title">
        Reset password.
      </h1>
      <div class="o-quotes_container">
        <div class="profile-section profile-bookmarklet">
          <p>
            Click the link below to request a new password for your account.
          </p>
          <%= link_to "Request a new password", request_password_reset_path, :class => "c-button c-button--primary" %>
        </div>
      </div>
    <% end %>
    <% if @section.eql?("bookmarklet") %>
      <h1 class="o-content_container__title settings-title">
        Bookmarklet.
      </h1>
      <div class="o-quotes_container">
        <div class="profile-section profile-bookmarklet">
          <p>
            If you need to re-install your bookmarklet, please refer to<br/>Ettúi's <%= link_to "installation instructions", introduction_path %>.
          </p>
        </div>
      </div>
    <% end %>
      <!-- <div class="profile-section profile-data profile-infographics">
        <div class="graph">
          <p class="subtitle subtitle--all-caps">Quotes</p>
          <h1><%= @user.quote_count %></h1>
        </div>
        <div class="graph">
          <p class="subtitle subtitle--all-caps">Sites</p>
          <h1><%= @user.source_count %></h1>
        </div>
        <div class="graph">
          <p class="subtitle subtitle--all-caps">Tags</p>
          <h1><%= @user.tag_count %></h1>
        </div>
      </div> -->
    </div>
  </div>
</div>

app/views/users/request_password_reset.html.erb
<% if flash[:notice] %>
  <div class="c-status_message"><%= flash[:notice] %></div>
<% end %>
<div class="o-overlay t-theme2">
  <div class="c-modal__window">
    <div class="modal__content">
      <%= link_to "ettúi", '/', class: "c-ettui-logo" %>
      <h1>
        Request a new password.
      </h1>
      <%= form_tag(send_password_reset_path, method: :post, class: "user-form") do -%>
        <div class="last field">
          <%= email_field_tag 'email', (@user.email unless @user.nil?), :placeholder => "mail@example.com" %>
        </div>
        <div class="actions">
          <%= submit_tag "Reset password", class: "stay button" %>
        </div>
      <% end %>
      <p>
        Instructions are e-mailed to you instantly<br/> and remain valid for an hour.
      </p>
    </div>
  </div>
</div>

app/views/users/reset_password.html.erb
<div class="c-status_message"><%= "Set a new password for #{@user.email}" %></div>
<div class="o-overlay t-theme2">
  <div class="c-modal__window">
    <div class="modal__content">
      <%= link_to "ettúi", '/', class: "c-ettui-logo" %>
      <h1>
        Enter a new password.
      </h1>
      <%= form_tag(update_password_path(@user.id), method: :put, class: "user-form") do -%>
        <div class="last field">
          <%= password_field_tag 'password', nil, :placeholder => "Enter a new password…" %>
        </div>
        <div class="actions">
          <%= submit_tag "Update password", class: "stay button" %>
        </div>
      <% end %>
      <p>
        A good password contains both upper and lower case letters along with numbers as well as special characters.
      </p>
    </div>
  </div>
</div>