config/routes.rb
Well::Application.routes.draw do
 
  root to: "welcome#index"

  get "logout" => "sessions#destroy", as: "logout"
  get "login" => "sessions#new", as: "login"
  get "signup" => "signup#index"
  get "profile/(:section)" => "users#profile", as: "profile"
  get 'demo' => "users#demo", as: "demo"
  get 'users/request_password_reset' => 'users#request_password_reset', as: "request_password_reset"
  post 'users/send_password_reset' => 'users#send_password_reset', as: "send_password_reset"
  get 'reset/(:password_reset_token)' => 'users#reset_password', as: "reset_password"
  put 'users/(:id)/update_password' => 'users#update_password', as: "update_password"

  # TODO: A welcome view:
  # "Welcome to Ettúi, {let's get started}"

  get "bookmarklet/preview" => "jsonp#preview", as: "bookmarklet_preview"
  get "legal/tos"
  get "legal/pp"
  get "demo/complete" => "users#complete", as: "completion"
  get "introduction/start", as: "introduction"
  get "introduction/trying_it"
  get "introduction/finish"
  get "json_quote_creation", controller: "json"
  get "json_tag_creation", controller: "json"
  get "quote_creation", controller: "jsonp"
  get "tag_creation", controller: "jsonp"
  resources :users, except: [:index, :profile]
  resources :sessions, only: [:new, :create, :destroy]
  resources :boards, only: [:show] do
    resources :quotes, only: [:destroy, :show] do
      resources :tags, only: [:destroy, :create]
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/views/welcome/index.html.erb
<div class="t-theme2">
  <%= render "header" %>
  <main class="introduction">
    <div class="c-landing_page__content">
      <h1 class="c-landing_page__title">
         You should always have the great things you’ve read with you.
      </h1>
      <p class="c-landing_page__text">  
        That is why we designed a service to easily save & catalogue those gems, so that they’re accessible from anywhere—at any time.
      </p>
      <div class="c-landing_page__actions">
        <% if current_user.nil? %>
          <%= link_to "Try our demo", demo_path, class: "c-button c-button--secondary" %>
        <% end %>
        <%= link_to "Create an account", signup_path, class: "c-button c-button--primary" %>
      </div>
      </div>
    <div style="display: flex; justify-content: center;">
      <div class="c-viewport">
        <%= image_tag "device-ipadmini-outlined.svg", class: "c-viewport__frame" %>
        <%= image_tag "ettui-ipad-2.png", class: "c-viewport__content" %>
      </div>
    </div>
  </div>
</div>
<footer class="c-landing_page__footer">
  <h1 class="c-ettui-logo">ettúi.</h1>
  <p class="c-landing_page__footer_title">Det e vej saum ha jott denna sejda.<br/>Henrik Wiberg å Hannes Gustafsson.</p>
</footer>