config/routes.rb
Well::Application.routes.draw do
 
  root to: "welcome#index"

  get "logout" => "sessions#destroy", as: "logout"
  get "login" => "sessions#new", as: "login"
  get "signup" => "signup#index"
  get "profile/(:section)" => "users#profile", as: "profile"
  get 'demo' => "users#demo", as: "demo"
  get 'users/request_password_reset' => 'users#request_password_reset', as: "request_password_reset"
  post 'users/send_password_reset' => 'users#send_password_reset', as: "send_password_reset"
  get 'reset/(:password_reset_token)' => 'users#reset_password', as: "reset_password"
  put 'users/(:id)/update_password' => 'users#update_password', as: "update_password"

  # TODO: A welcome view:
  # "Welcome to Ettúi, {let's get started}"

  get "bookmarklet/preview" => "jsonp#preview", as: "bookmarklet_preview"
  get "legal/tos"
  get "legal/pp"
  get "demo/complete" => "users#complete", as: "completion"
  get "introduction/start", as: "introduction"
  get "introduction/trying_it"
  get "introduction/finish"
  get "json_quote_creation", controller: "json"
  get "json_tag_creation", controller: "json"
  get "quote_creation", controller: "jsonp"
  get "tag_creation", controller: "jsonp"
  resources :users, except: [:index, :profile]
  resources :sessions, only: [:new, :create, :destroy]
  resources :boards, only: [:show] do
    resources :quotes, only: [:destroy, :show] do
      resources :tags, only: [:destroy, :create]
    end
  end
end

app/models/board.rb
class Board < ActiveRecord::Base

  has_and_belongs_to_many :quotes
  has_and_belongs_to_many :users, join_table: :subscriptions
  has_many :tags, through: :quotes
  has_many :sources, through: :quotes

  def unread(user_last_active_at)
      self.quotes.order(created_at: :desc).where("created_at > ?", user_last_active_at).to_a
  end

  def tag_count tag
    tags.where(name: tag.name).count
  end

  def unique_tags
      tags.distinct
  end

  def source_count source
    sources.where(id: source.id).count
  end

  def has_subscribers?
      users.count > 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_path unless current_user
  end
end

app/views/application/_bookmarklet.html.erb
<div class="noted-content-container">
  <h1 class="status-message"><%= title %></h1>
  <h1 class="sub-message"><%= subtitle %></h1>

  <!-- Only render the tag-container if there are tags. !-->
  <% if tags.any? %>
    <div class='tag-container'>
      <% tags.each do |tag| %>
        <% if tag.is_existing %>
          <li class="noted-tag tid-<%= tag.id %> selected"><%= tag.name %></li>
        <% else %>
          <li class="noted-tag tid-<%= tag.id %>"><%= tag.name %></li>
        <% end %>
      <% end %>
    </div>
  <% end %>
  <div class='add-tag-container'>
    <input type='text' id='noted-new-tag' placeholder='Type a new tag and press enter'>
    <input type='submit' id='noted-new-tag-submit' value='Add tag'>
  </div>
  <a href='#!' onclick='closeBookmarkletWindow()' id='noted-close-btn'>Close window</a>
</div>

app/views/application/_header.html.erb
<header>
  <h1 class="c-ettui-logo">ettúi.</h1>
  <div>
    <% if current_user %>
      <%= link_to "Logout", logout_path, class: "subtitle--all-caps header__link secondary" %>
      <% if current_user.twitter_image_url.nil? %>
        <%= link_to current_user.name || current_user.email, board_path(current_user.boards.first), {:style=> 'background-color: rgba(0, 0, 0, .07); padding: 1px 6px 3px; border-radius: 8px; color: #666; font-weight: 600; max-width: 100px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;'} %>
      <% else %>
        <%= link_to image_tag(current_user.twitter_image_url, class: "a-profile_image"), board_path(current_user.boards.first) %>
      <% end %>
    <% else %>
      <%= link_to "Try our demo", demo_path, class: "subtitle--all-caps header__link secondary" %>
      <%= link_to "Sign in", login_path, class: "subtitle--all-caps header__link secondary" %>
    <% end %>
  </div>
</header>

app/views/application/_sidebar_filter_list.html.erb
<ol class="c-sidebar_container__list">
  <% filters.each do |filter| %>
    <%= render partial:
      "sidebar_#{filter.class.name.downcase}",
      locals: {
        filter_item: filter
      }
    %>
  <% end %>
</ol>

app/views/application/_sidebar_search_field.html.erb
<div class="c-sidebar_container__search">
    <%= form_for @search, url: board_path(@board), method: :get do |f| %>
        <% @search.tag_ids.each do |id|%>
            <%= hidden_field_tag "search[tag_ids][]", id %>
        <% end %>
        <% @search.source_ids.each do |id|%>
            <%= hidden_field_tag "search[source_ids][]", id %>
        <% end %>
        <%= fa_icon 'search' %>
        <%= f.text_field :query, placeholder: "Search for a quote…" %>
        <%= f.submit "Search", class: 'submit', name: nil %>
    <% end %>
</div>

app/views/application/_sidebar_source.html.erb
<li class="<%= @search.source_classes(filter_item) %>" >
  <img class="c-quote__favicon" src="<%= filter_item.favicon %>"></img>
  <%= link_to filter_item.hostname.truncate(30), board_path(@board, @search.update_params_for(filter_item))
  %>
  <p class="c-sidebar_container__count"><%= filter_item.count_for(@board) %></p>
</li>

app/views/application/_sidebar_tag.html.erb
<li class="<%= @search.tag_classes(filter_item) %>">
  <%= link_to filter_item.name.truncate(30), board_path(@board, @search.update_params_for(filter_item)), class: "c-tag__name" %>
  <p class="c-sidebar_container__count"><%= filter_item.count_for(@board) %></p>
</li>